name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, test, and build the library
        run: |
          yarn
          yarn test
          yarn prepack
