on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Lint and format
        run: bun format

      - name: Type check
        run: bun typecheck

      - name: Test
        run: bun test
